language: node_js
node_js: stable

before_script:
  - npm i -g typescript
  - mkdir -p out
  - mkdir -p out/src
  - mkdir -p out/src/content
  - cp src/content/page.html out/src/content/page.html
  - cp src/content/default.css out/src/content/default.css
  - node node_modules/typescript/bin/tsc --project .

after_script:
  - npm run coveralls

cache:
  directories:
    - node_modules
